# Generated by Django 6.0.5 on 2026-05-28 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ColorTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_nav', models.CharField(default='#000', max_length=256)),
                ('fg_nav', models.CharField(default='#ffff00e0', max_length=256)),
                ('bg_icon', models.CharField(default='#6A769988', max_length=256)),
                ('fg_icon', models.CharField(default='#ffffffa0', max_length=256)),
                ('bg_caption', models.CharField(default='#000', max_length=256)),
                ('fg_caption', models.CharField(default='#ffffff', max_length=256)),
                ('bg_tab', models.CharField(default='#ffff2040', max_length=256)),
                ('fg_tab', models.CharField(default='#00000060', max_length=256)),
                ('bg_thead', models.CharField(default='#fff0f06', max_length=256)),
                ('fg_thead', models.CharField(default='#000', max_length=256)),
                ('bg_table_odd', models.CharField(default='#ffff', max_length=256)),
                ('fg_table_odd', models.CharField(default='#000', max_length=256)),
                ('bg_table_even', models.CharField(default='#fffa', max_length=256)),
                ('fg_table_even', models.CharField(default='#000', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(default='This Element has no description.')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Equipment Name')),
                ('description', models.TextField(blank=True, max_length=256, verbose_name='Narrative description')),
                ('rules', models.TextField(blank=True, max_length=256, verbose_name='Rules')),
                ('cost', models.IntegerField(default=1, verbose_name='Generic Point Cost')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('title', models.CharField(max_length=32)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, default='-', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OptionalRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
                ('cost', models.IntegerField(default=0)),
                ('per_mini', models.BooleanField(default=False, verbose_name='Cost per miniature')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stratagem',
            fields=[
                ('title', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('narrative', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('cost', models.IntegerField(verbose_name='PM Needed')),
                ('cost_alt', models.IntegerField(verbose_name='PM Needed for alternatives / Recast')),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('range', models.IntegerField(default=10)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('s', models.IntegerField(blank=True, default=5, null=True)),
                ('ap', models.IntegerField(blank=True, default=5, null=True)),
                ('d', models.CharField(blank=True, default='', max_length=5)),
                ('abilities', models.TextField(default='--')),
            ],
        ),
        migrations.CreateModel(
            name='WeaponType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(default='This WeaponType has no description')),
            ],
        ),
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(default='This Faction has no description.')),
                ('keywords', models.ManyToManyField(blank=True, to='dmscreen.keyword')),
            ],
        ),
        migrations.CreateModel(
            name='Army',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('font', models.CharField(default='Times new Roman', max_length=32)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmscreen.game')),
                ('stratagems', models.ManyToManyField(blank=True, to='dmscreen.stratagem')),
            ],
        ),
        migrations.CreateModel(
            name='Troop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Troop Name')),
                ('i', models.IntegerField(default=5, verbose_name=' M/I  (Movimiento)')),
                ('ws', models.IntegerField(default=5, verbose_name='WS/HA (H.Armas)')),
                ('bs', models.IntegerField(default=5, verbose_name='BS/HP (H.Proyectiles)')),
                ('s', models.IntegerField(default=5, verbose_name=' S/F  (Fuerza)')),
                ('t', models.IntegerField(default=5, verbose_name=' T/R  (Resistencia)')),
                ('w', models.IntegerField(default=5, verbose_name=' W/H  (Heridas)')),
                ('a', models.IntegerField(default=5, verbose_name='  A   (Ataques)')),
                ('ld', models.IntegerField(default=5, verbose_name='  L   (Liderazgo)')),
                ('sv', models.IntegerField(default=5, verbose_name='  S   (Salvacion)')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('abilities', models.ManyToManyField(blank=True, to='dmscreen.ability')),
                ('keywords', models.ManyToManyField(blank=True, to='dmscreen.keyword')),
            ],
        ),
        migrations.CreateModel(
            name='TroopChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField(default=0, verbose_name='Replacement cost')),
                ('count', models.IntegerField(default=1, verbose_name='Number of Replacements allowed')),
                ('replacement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='after', to='dmscreen.troop', verbose_name='New Troop')),
                ('troop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='before', to='dmscreen.troop', verbose_name='Previous Troop')),
            ],
        ),
        migrations.CreateModel(
            name='TroopEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField(blank=True, default=None, null=True, verbose_name='Cost override')),
                ('e', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='te', to='dmscreen.equipment', verbose_name='Equipment')),
                ('t', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tt', to='dmscreen.troop', verbose_name='Troop')),
            ],
        ),
        migrations.AddField(
            model_name='troop',
            name='equipment',
            field=models.ManyToManyField(blank=True, to='dmscreen.troopequipment'),
        ),
        migrations.CreateModel(
            name='TroopSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('cost', models.IntegerField(default=1, verbose_name='Cost per mini')),
                ('power', models.IntegerField(default=1, verbose_name='Power added to the unit if this option is taken')),
                ('alternative', models.BooleanField(default=False, verbose_name='True if this an alternative to another troopset')),
                ('troop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmscreen.troop')),
            ],
        ),
        migrations.CreateModel(
            name='UnitEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField(blank=True, default=None, null=True, verbose_name='Cost override')),
                ('e', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ue', to='dmscreen.equipment', verbose_name='Equipment')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('subtitle', models.CharField(blank=True, max_length=64, null=True)),
                ('power', models.IntegerField(default=5)),
                ('abilities', models.ManyToManyField(blank=True, related_name='abilities', to='dmscreen.ability', verbose_name='Unit Abilities')),
                ('army', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dmscreen.army')),
                ('element', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dmscreen.element')),
                ('faction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dmscreen.faction')),
                ('keywords', models.ManyToManyField(blank=True, related_name='keywords', to='dmscreen.keyword', verbose_name='Unit Keywords')),
                ('opt_rules', models.ManyToManyField(blank=True, related_name='opt_rules', to='dmscreen.optionalrule', verbose_name='Optional Rules')),
                ('opt_troops', models.ManyToManyField(blank=True, related_name='opt_troops', to='dmscreen.troopset', verbose_name='Optional Troops')),
                ('replacements', models.ManyToManyField(blank=True, to='dmscreen.troopchange', verbose_name='Troop Replacements')),
                ('specialrules', models.ManyToManyField(blank=True, related_name='specialrules', to='dmscreen.specialrule', verbose_name='Special Rules')),
                ('transport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dmscreen.transport')),
                ('troops', models.ManyToManyField(blank=True, related_name='troops', to='dmscreen.troopset', verbose_name='Troop Composition')),
                ('equipment', models.ManyToManyField(blank=True, related_name='unitequipment', to='dmscreen.unitequipment', verbose_name='Unit Equipment')),
            ],
        ),
        migrations.AddField(
            model_name='troop',
            name='weapons',
            field=models.ManyToManyField(blank=True, to='dmscreen.weapon'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dmscreen.weapontype'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='types',
            field=models.ManyToManyField(blank=True, related_name='weapontype', to='dmscreen.weapontype'),
        ),
    ]
